<?php $product = $block->getProduct(); ?>
<?php $helper = $this->helper("ALevel\QuickOrder\Helper\Data"); ?>
<?php $buttonTitle = $helper->getConfig('quickorder/general/button_title'); ?>

<?php $postParams = $block->getProductParams($product);
print_r($postParams);?>

<div class="quickorder-btn">
    <button type="submit"
            title="<?php echo $block->escapeHtml(__($buttonTitle)); ?>"
            class="action tocart quickorder primary"
            id="product-callback-button-<?php echo $postParams['id']?>"
            >
        <span><?php /* @noEscape */ echo __($buttonTitle) ?></span>
    </button>
</div>



    <div data-role="focusable-scope" id="popup_modal_<?php echo $postParams['id']?>">
            <div id="popupmodal" style="">
                <div style="margin-top:20px;">
                    <div class="showerror"></div>
                        <table id="callback" border="0" cellspacing="0" cellpadding="0">
                            <tbody>
                            <input name="callback_sku" id="callback_sku_<?php echo $postParams['sku']?>" value="<?php echo $block->getProductParams($product)['sku']?>" type="text" hidden>
                            <tr>
                                <td style="width:20%;"><strong>Name*</strong></td>
                                <td>:</td>
                                <td>
                                    <input name="callback_name" id="callback_name_<?php echo $postParams['id']?>" class="required-entry" value="" style="width:80%;" type="text">
                                </td>
                            </tr>
                            <tr>
                                <td style="width:20%;"><strong>Phone*</strong></td>
                                <td>:</td>
                                <td>
                                    <input name="callback_phone" id="callback_phone_<?php echo $postParams['id']?>" class="required-entry" value="" style="width:80%;" type="text"><br/>
                                </td>
                            </tr>
                            <tr>
                                <td style="width:20%;"><strong>Email</strong></td>
                                <td>:</td>
                                <td>
                                    <input name="callback_email" type="email" id="callback_email_<?php echo $postParams['id']?>" class="" value="" style="width:80%;" type="email"><br/>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="save_date" id="submit_button_<?php echo $postParams['id']?>">
                            <button type="submit"><?php echo __('Send'); ?></button>
                        </div>
                </div>
            </div>
    </div>


<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Quick Order Information',
                buttons: []
                // [{
                //     text: $.mage.__('Continue'),
                //     class: '',
                //     id: 'submit_button_<?php echo $postParams['id']?>'
                //     click: function () {
                //         this.closeModal();
                //     }
                // }]
            };

            var popup = modal(options, $('#popup_modal_<?php echo $postParams['id']?>'));
            $("#product-callback-button-<?php echo $postParams['id']?>").on('click',function(){
                $("#popup_modal_<?php echo $postParams['id']?>").modal("openModal");
                // $(this).remove();
            });

            var url = '<?php echo $block->getAjax(); ?>';

            $("#submit_button_<?php echo $postParams['id']?>").on('click',function(){
                var sku    = $("#callback_sku_<?php echo $postParams['sku']?>").val();
                var name    = $("#callback_name_<?php echo $postParams['id']?>").val();
                var phone   = $("#callback_phone_<?php echo $postParams['id']?>").val();
                var email   = $("#callback_email_<?php echo $postParams['id']?>").val();
            console.log(url);
            console.log(name);
            console.log(sku);
            console.log(phone);
            console.log(email);
            console.log('<?php echo $block->getFormKey() ?>');


                
                $.ajax({
                type: "POST",
                url: url + '?name=' + name  + '&mail=' + email + '&phone=' + phone + '&product_sku=' + sku,
                contentType: false,
                cache: false,
                processData: false,
                data: {form_key: '<?php echo $block->getFormKey() ?>'},
                success: function () {
                  $("#popup_modal_<?php echo $postParams['id']?>").modal("closeModal");
                    console.log('dddddddddddd');
                },  

                error: function(XMLHttpRequest, textStatus, errorThrown) { 
                    alert("Status: " + textStatus); alert("Error: " + errorThrown); 
                },  

                showLoader: true
                });
                
            });
        }
    );
</script>